apiVersion: v1
kind: Service
metadata:
  name: data-warehouse
  labels:
    app: data-warehouse
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 30000
  selector:
    app: data-warehouse
