# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import broker_pb2 as broker__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class PublisherServiceStub(object):
    """Publisher service - handles message publishing
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishMessage = channel.unary_unary(
                '/broker.PublisherService/PublishMessage',
                request_serializer=broker__pb2.PublishRequest.SerializeToString,
                response_deserializer=broker__pb2.PublishResponse.FromString,
                )
        self.PublishBatch = channel.stream_unary(
                '/broker.PublisherService/PublishBatch',
                request_serializer=broker__pb2.PublishRequest.SerializeToString,
                response_deserializer=broker__pb2.PublishResponse.FromString,
                )
        self.GetPublisherHealth = channel.unary_unary(
                '/broker.PublisherService/GetPublisherHealth',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=broker__pb2.HealthResponse.FromString,
                )


class PublisherServiceServicer(object):
    """Publisher service - handles message publishing
    """

    def PublishMessage(self, request, context):
        """Publish a single message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishBatch(self, request_iterator, context):
        """Publish multiple messages in a batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublisherHealth(self, request, context):
        """Check publisher health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PublisherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishMessage,
                    request_deserializer=broker__pb2.PublishRequest.FromString,
                    response_serializer=broker__pb2.PublishResponse.SerializeToString,
            ),
            'PublishBatch': grpc.stream_unary_rpc_method_handler(
                    servicer.PublishBatch,
                    request_deserializer=broker__pb2.PublishRequest.FromString,
                    response_serializer=broker__pb2.PublishResponse.SerializeToString,
            ),
            'GetPublisherHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublisherHealth,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=broker__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'broker.PublisherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PublisherService(object):
    """Publisher service - handles message publishing
    """

    @staticmethod
    def PublishMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broker.PublisherService/PublishMessage',
            broker__pb2.PublishRequest.SerializeToString,
            broker__pb2.PublishResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PublishBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/broker.PublisherService/PublishBatch',
            broker__pb2.PublishRequest.SerializeToString,
            broker__pb2.PublishResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPublisherHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broker.PublisherService/GetPublisherHealth',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            broker__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SubscriberServiceStub(object):
    """Subscriber service - handles message subscriptions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/broker.SubscriberService/Subscribe',
                request_serializer=broker__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=broker__pb2.Message.FromString,
                )
        self.SubscribeWithFilter = channel.unary_stream(
                '/broker.SubscriberService/SubscribeWithFilter',
                request_serializer=broker__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=broker__pb2.Message.FromString,
                )
        self.Unsubscribe = channel.unary_unary(
                '/broker.SubscriberService/Unsubscribe',
                request_serializer=broker__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=broker__pb2.UnsubscribeResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/broker.SubscriberService/Heartbeat',
                request_serializer=broker__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=broker__pb2.HeartbeatResponse.FromString,
                )
        self.GetHistoricalMessages = channel.unary_stream(
                '/broker.SubscriberService/GetHistoricalMessages',
                request_serializer=broker__pb2.HistoryRequest.SerializeToString,
                response_deserializer=broker__pb2.Message.FromString,
                )


class SubscriberServiceServicer(object):
    """Subscriber service - handles message subscriptions
    """

    def Subscribe(self, request, context):
        """Subscribe to topics and receive real-time messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeWithFilter(self, request, context):
        """Subscribe to specific topics with filtering
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Unsubscribe from topics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Send heartbeat to maintain connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricalMessages(self, request, context):
        """Get historical messages for subscribed topics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubscriberServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=broker__pb2.SubscribeRequest.FromString,
                    response_serializer=broker__pb2.Message.SerializeToString,
            ),
            'SubscribeWithFilter': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeWithFilter,
                    request_deserializer=broker__pb2.SubscribeRequest.FromString,
                    response_serializer=broker__pb2.Message.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=broker__pb2.UnsubscribeRequest.FromString,
                    response_serializer=broker__pb2.UnsubscribeResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=broker__pb2.HeartbeatRequest.FromString,
                    response_serializer=broker__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetHistoricalMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.GetHistoricalMessages,
                    request_deserializer=broker__pb2.HistoryRequest.FromString,
                    response_serializer=broker__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'broker.SubscriberService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SubscriberService(object):
    """Subscriber service - handles message subscriptions
    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/broker.SubscriberService/Subscribe',
            broker__pb2.SubscribeRequest.SerializeToString,
            broker__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeWithFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/broker.SubscriberService/SubscribeWithFilter',
            broker__pb2.SubscribeRequest.SerializeToString,
            broker__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broker.SubscriberService/Unsubscribe',
            broker__pb2.UnsubscribeRequest.SerializeToString,
            broker__pb2.UnsubscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broker.SubscriberService/Heartbeat',
            broker__pb2.HeartbeatRequest.SerializeToString,
            broker__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHistoricalMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/broker.SubscriberService/GetHistoricalMessages',
            broker__pb2.HistoryRequest.SerializeToString,
            broker__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DashboardServiceStub(object):
    """Dashboard/Monitoring service - provides system status and metrics
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBrokerStatus = channel.unary_unary(
                '/broker.DashboardService/GetBrokerStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=broker__pb2.BrokerStatus.FromString,
                )
        self.GetSystemStats = channel.unary_unary(
                '/broker.DashboardService/GetSystemStats',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=broker__pb2.SystemStats.FromString,
                )
        self.GetRecentMessages = channel.unary_unary(
                '/broker.DashboardService/GetRecentMessages',
                request_serializer=broker__pb2.MessageQueryRequest.SerializeToString,
                response_deserializer=broker__pb2.MessageQueryResponse.FromString,
                )
        self.GetTopics = channel.unary_unary(
                '/broker.DashboardService/GetTopics',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=broker__pb2.TopicsResponse.FromString,
                )
        self.GetSubscribers = channel.unary_unary(
                '/broker.DashboardService/GetSubscribers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=broker__pb2.SubscribersResponse.FromString,
                )
        self.StreamSystemEvents = channel.unary_stream(
                '/broker.DashboardService/StreamSystemEvents',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=broker__pb2.SystemEvent.FromString,
                )


class DashboardServiceServicer(object):
    """Dashboard/Monitoring service - provides system status and metrics
    """

    def GetBrokerStatus(self, request, context):
        """Get broker status information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStats(self, request, context):
        """Get system statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentMessages(self, request, context):
        """Get recent messages with pagination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopics(self, request, context):
        """Get list of topics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubscribers(self, request, context):
        """Get list of active subscribers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSystemEvents(self, request, context):
        """Stream real-time system events for monitoring
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DashboardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBrokerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBrokerStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=broker__pb2.BrokerStatus.SerializeToString,
            ),
            'GetSystemStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStats,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=broker__pb2.SystemStats.SerializeToString,
            ),
            'GetRecentMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentMessages,
                    request_deserializer=broker__pb2.MessageQueryRequest.FromString,
                    response_serializer=broker__pb2.MessageQueryResponse.SerializeToString,
            ),
            'GetTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopics,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=broker__pb2.TopicsResponse.SerializeToString,
            ),
            'GetSubscribers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubscribers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=broker__pb2.SubscribersResponse.SerializeToString,
            ),
            'StreamSystemEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSystemEvents,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=broker__pb2.SystemEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'broker.DashboardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DashboardService(object):
    """Dashboard/Monitoring service - provides system status and metrics
    """

    @staticmethod
    def GetBrokerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broker.DashboardService/GetBrokerStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            broker__pb2.BrokerStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSystemStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broker.DashboardService/GetSystemStats',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            broker__pb2.SystemStats.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecentMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broker.DashboardService/GetRecentMessages',
            broker__pb2.MessageQueryRequest.SerializeToString,
            broker__pb2.MessageQueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broker.DashboardService/GetTopics',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            broker__pb2.TopicsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSubscribers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broker.DashboardService/GetSubscribers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            broker__pb2.SubscribersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamSystemEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/broker.DashboardService/StreamSystemEvents',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            broker__pb2.SystemEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class RaftServiceStub(object):
    """RAFT Consensus service - handles distributed consensus
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/broker.RaftService/RequestVote',
                request_serializer=broker__pb2.VoteRequest.SerializeToString,
                response_deserializer=broker__pb2.VoteResponse.FromString,
                )
        self.AppendEntries = channel.unary_unary(
                '/broker.RaftService/AppendEntries',
                request_serializer=broker__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=broker__pb2.AppendEntriesResponse.FromString,
                )
        self.GetRaftStatus = channel.unary_unary(
                '/broker.RaftService/GetRaftStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=broker__pb2.RaftStatus.FromString,
                )
        self.InstallSnapshot = channel.unary_unary(
                '/broker.RaftService/InstallSnapshot',
                request_serializer=broker__pb2.InstallSnapshotRequest.SerializeToString,
                response_deserializer=broker__pb2.InstallSnapshotResponse.FromString,
                )


class RaftServiceServicer(object):
    """RAFT Consensus service - handles distributed consensus
    """

    def RequestVote(self, request, context):
        """Request vote from other nodes during leader election
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Append log entries (including heartbeats)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRaftStatus(self, request, context):
        """Get current RAFT status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallSnapshot(self, request, context):
        """Install snapshot for catching up lagging nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=broker__pb2.VoteRequest.FromString,
                    response_serializer=broker__pb2.VoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=broker__pb2.AppendEntriesRequest.FromString,
                    response_serializer=broker__pb2.AppendEntriesResponse.SerializeToString,
            ),
            'GetRaftStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRaftStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=broker__pb2.RaftStatus.SerializeToString,
            ),
            'InstallSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallSnapshot,
                    request_deserializer=broker__pb2.InstallSnapshotRequest.FromString,
                    response_serializer=broker__pb2.InstallSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'broker.RaftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RaftService(object):
    """RAFT Consensus service - handles distributed consensus
    """

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broker.RaftService/RequestVote',
            broker__pb2.VoteRequest.SerializeToString,
            broker__pb2.VoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broker.RaftService/AppendEntries',
            broker__pb2.AppendEntriesRequest.SerializeToString,
            broker__pb2.AppendEntriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRaftStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broker.RaftService/GetRaftStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            broker__pb2.RaftStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InstallSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/broker.RaftService/InstallSnapshot',
            broker__pb2.InstallSnapshotRequest.SerializeToString,
            broker__pb2.InstallSnapshotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
